### ISSUE TITLE
Database roadmap

### ISSUE THREAD

**Issue by niemand-01** [KITKryptoDAO/NoFraudToken#1]
Hi @AtmanDai,

This ticket acts as a master ticket encompassing the rough roadmap to arrive at proper "backend" state. Any time you made progress, U can write it in comment below.

## Overview

Let´s first recap what would end product for database look like: A package in JS, which can provide several CRUD (create read update and delete) interface to frontend. 

## Roadmap

- The file storage system is chosen for IPFS (interplanetary file system), which is a decentralized database that we need to access the content via a node / gateway provider. For this case, we suggest to use [INFURA](https://docs.infura.io/networks/ipfs/how-to/access-ipfs-content/dedicated-gateways#stats-and-billing) for our gateway provider, which has a free tier of 5GB memory usage.
- As we are both new to the topic, it´s suggested to start small with a minimal viable example that works with manual intervention. I propose the following procedure:
  - Setup an account in INFURA and register our [domain ](https://docs.infura.io/networks/ipfs/how-to/access-ipfs-content/dedicated-gateways#choose-a-unique-subdomain)name of IFPS. 
  - Get familar with the INFURA API to interact with IFPS, by manually create a file, pin it, read it and delete it. Tutorial can be found [here](https://docs.infura.io/networks/ipfs/how-to/manage-files#read-a-file).
  - Try to find out if INFURA provide API for update. If not, try with following proxy: read-update locally-upload and override original file.
  - Create a JS Package following this [tutorial ](https://dev.to/adhamniazy/how-to-upload-images-to-ipfs-using-infuraio-dedicated-gateways-11c6)that automate the procedure mentioned above.
  - Use chai & mocha to create test files for package written above: following this [tutorial](https://www.browserstack.com/guide/unit-testing-for-nodejs-using-mocha-and-chai).
- Align with frontend team to test usage of current package. A simple workflow would be: 
  - (Front end & smart contract) User click burn button, which invoke smart contract to execute `_burn` or `batch_burn` functions, callback was executed: which will trigger our function
  - (Database) The information in JSON format from front end will be saved with a unique identifier into IPFS. How can we name this unique identifier can be discussed which will be needed to retrieve the underlying if needed: one proposal would be: `unix_timestamp` + hash of bundle addresses of fraudulent NFTs (User address might be better, as it´s critical for retrieve accidentally deleted valuable nft from vault, so maybe hashed address?)

## Potential problems:
- Infura moved public gateway to dedicated gateway, so we shall stick to the latest workflow: https://dev.to/adhamniazy/how-to-upload-images-to-ipfs-using-infuraio-dedicated-gateways-11c6
- ipfshttpclient needs to be added in container package: https://pypi.org/project/ipfshttpclient/
- As elaborated, INFURA might not support update API, which is a question whether we need it in production or not.

Regards,
@niemand-01

**Comment by AtmanDai** [comment]
To @niemand-01 @hannesgao ,

Works that have been done so far are following:
Because temporarily INFURA does not provide new  IPFS keys anymore, we decide to use [Pinata](https://www.pinata.cloud/) instead and the [SDK](https://www.npmjs.com/package/@pinata/sdk?activeTab=readme#pinJSONToIPFS-anchor) provided by it. 
Based on this platform, we built our own IPFS dedicated gateway and uploaded, updated, deleted files both manually and by using JS packages automatically. 

In the next step we want to align with frontend team to test usage of current package. For this purpose we may need to create two functions that are callable by frontend. One is UPLOAD, which can upload JSON objects that contain the metadata of burnt NFTs to our IPFS node. The other one is READ, which can query NFTs with its metadata like user address and delete timestamp.
Further works, especially the contents of JSON objects and format of metadata, need more discussion and communication between group members.

Best Regards,
@AtmanDai

**Comment by hannesgao** [comment]
@AtmanDai Pinata could be a temporary solution for our demo, good job. 

As we discussed in our audio conference on 2023.12.03 in the morning, for subsequent project iterations and commercial product, we still consider it a priority to deploy this database on our centralized servers and not open access to the public. 

For the demo, the JSON file submitted by the front-end will be directly post to IPFS, but the encrypted storage of the API key of Pinata still needs to be considered. Perhaps we need some sort of session based authentication mechanism to ensure that front-end calls to the database API are authorized, reasonable and not abused.
